name: Build and Release

on:
  schedule:
    - cron: '0 18 * * 4'
  workflow_dispatch:
    # inputs:
    #   tag_name:
    #     description: 'Tag name (e.g., v1.0.0)'
    #     required: true
  # push:
  #   branches:
  #     - main
  #   tags:
  #     - '*'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Check build space
        run: |
          df -h
          lsblk
          free -h
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 10240
          swap-size-mb: 1024
          remove-dotnet: 'false'
      - name: Check build space after maximize-build-space
        run: |
          df -h
          lsblk
          free -h
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup environment
        run: |
          sudo ./install-env.sh
      - name: Prepare
        run: |
          ./prepare.sh
      - name: Cache OpenWrt dl and toolchain
        uses: actions/cache@v3
        if: always()
        with:
          path: |
            lede/dl
            lede/staging_dir
#            lede/build_dir
          key: ${{ runner.os }}-openwrt-${{ hashFiles('lede/feeds.conf.default', 'xgp.config') }}
      - name: Build
        run: |
          ./build.sh
      - name: Prepare release assets
        run: |
          mkdir -p release_assets
          cp lede/bin/targets/rockchip/armv8/*.img.gz release_assets/ || true
          cp lede/bin/targets/rockchip/armv8/openwrt-rockchip-armv8-nlnet_xiguapi-v3.manifest release_assets/ || true
          cp lede/bin/targets/rockchip/armv8/config.buildinfo release_assets/ || true
          cp lede/bin/targets/rockchip/armv8/feeds.buildinfo release_assets/ || true
          cp lede/bin/targets/rockchip/armv8/profiles.json release_assets/ || true
          cp lede/bin/targets/rockchip/armv8/version.buildinfo release_assets/ || true
          cp lede/bin/targets/rockchip/armv8/sha256sums release_assets/ || true
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: release_assets/
      - name: Calculate disk usage
        if: always()
        run: |
          df -h
          lsblk
          du -h --max-depth=2
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: release_assets/
      - name: List files
        run: |
          ls -lah
          ls -lah release_assets
      - name: Get current date and time for release info
        id: release-prepare
        run: |
          current_date=$(TZ=Asia/Shanghai date +'%y%m%d')
          current_time=$(TZ=Asia/Shanghai date +'%H%M%S')
          echo "current_date=${current_date}" >> $GITHUB_OUTPUT
          echo "current_time=${current_time}" >> $GITHUB_OUTPUT
          RELEASE_DATE=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
          VERSION=$(cat release_assets/version.buildinfo | grep '^r' | head -n 1)
          echo "RELEASE_TITLE=${RELEASE_DATE} - ${VERSION}" >> $GITHUB_OUTPUT
      - name: Create new tag if needed
        run: |
          git tag ${{ steps.check-changes.outputs.new_tag }}
          git push origin ${{ steps.check-changes.outputs.new_tag }}
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.check-changes.outputs.new_tag }}
          # tag_name: ${{ inputs.tag_name }}
          name: ${{ steps.release-prepare.outputs.RELEASE_TITLE }}
          body_path: release_assets/openwrt-rockchip-armv8-nlnet_xiguapi-v3.manifest
          files: |
            release_assets/*.img.gz
            release_assets/openwrt-rockchip-armv8-nlnet_xiguapi-v3.manifest
            release_assets/config.buildinfo
            release_assets/feeds.buildinfo
            release_assets/profiles.json
            release_assets/version.buildinfo
            release_assets/sha256sums
