name: Sync Upstream

on:
  # schedule:
  #   - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Sync Repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone --branch xgp git@github.com:zzzz0317/lede.git
          cd lede
          git remote add upstream git@github.com:coolsnowwolf/lede.git
          git fetch upstream master
          git merge upstream/master --no-edit
          git push origin xgp
